version: '2'
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"    
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "3001:3001" 
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - ./backend/database.sql:/docker-entrypoint-initdb.d/1-init.sql  
      - ./init_all.sh:/2-init_all.sh
